/**
 * Export functionality for analysis results
 * Supports JSON, Markdown, and PDF formats
 */

import { AnalysisResult } from '@/types';

/**
 * Helper function to safely convert timestamp to Date object
 * Handles both Date objects and ISO string timestamps from JSON serialization
 */
function ensureDate(timestamp: Date | string): Date {
  return timestamp instanceof Date ? timestamp : new Date(timestamp);
}

/**
 * Export analysis result as JSON
 */
export function exportAsJSON(result: AnalysisResult): void {
  const jsonString = JSON.stringify(result, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  downloadFile(blob, `remem-analysis-${result.id}.json`);
}

/**
 * Export analysis result as Markdown
 */
export function exportAsMarkdown(result: AnalysisResult): void {
  const timestamp = ensureDate(result.timestamp);
  const markdown = `# ReMem Cognitive Analysis Report

**Analysis ID:** ${result.id}
**Timestamp:** ${timestamp.toLocaleString()}

---

## Cognitive Recovery Score: ${result.recoveryScore.overall}/100

- **Context Completeness:** ${result.recoveryScore.contextCompleteness}%
- **Thread Clarity:** ${result.recoveryScore.threadClarity}%
- **Actionability:** ${result.recoveryScore.actionability}%

---

## ⚖️ Prosecutor Analysis
**What Went Wrong**

${result.prosecutorDefense.prosecutor.issues.map(issue => `- ${issue}`).join('\n')}

**Severity:** ${result.prosecutorDefense.prosecutor.severity}

---

## 🛡️ Defense Reasoning
**Why It Made Sense**

${result.prosecutorDefense.defense.reasons.map(reason => `- ${reason}`).join('\n')}

**Context:** ${result.prosecutorDefense.defense.context}

---

## ⚖️ Judge Summary

**Verdict:** ${result.prosecutorDefense.judge.verdict}

**Key Insight:**  
${result.prosecutorDefense.judge.keyInsight}

**Recommendation:**  
${result.prosecutorDefense.judge.recommendation}

---

## 🎯 Most Likely Next Actions

${result.nextActions.map((action, index) => 
  `${index + 1}. ${action.action} (Confidence: ${action.confidence}%)`
).join('\n')}

---

${result.gitTimeline ? `## 📊 Git Timeline

${result.gitTimeline.map(commit =>
  `- **[${commit.type}]** ${commit.message}
  _${commit.author} - ${ensureDate(commit.date).toLocaleDateString()}_`
).join('\n')}

---

` : ''}

## Input Context

\`\`\`
${result.inputText}
\`\`\`

---

*Generated by ReMem - Cognitive Restoration Engine*
`;

  const blob = new Blob([markdown], { type: 'text/markdown' });
  downloadFile(blob, `remem-analysis-${result.id}.md`);
}

/**
 * Export analysis result as PDF (simplified HTML version)
 * Note: For true PDF generation, you'd need a library like jsPDF or html2pdf
 */
export function exportAsPDF(result: AnalysisResult): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ReMem Analysis Report - ${result.id}</title>
  <style>
      body {
        font-family: monospace;
        max-width: 800px;
        margin: 40px auto;
        padding: 20px;
        line-height: 1.6;
        color: #00C853;
        background-color: white;
      }
      h1 { color: #00C853; border-bottom: 4px solid #00C853; padding-bottom: 10px; text-transform: uppercase; font-weight: 900; }
      h2 { color: white; background-color: #2D4CC8; padding: 10px; margin-top: 30px; text-transform: uppercase; border: 4px solid #00C853; box-shadow: 4px 4px 0px #00C853; }
      h3 { color: #D94A3D; text-transform: uppercase; font-weight: bold; }
      .score { font-size: 64px; font-weight: 900; color: #D94A3D; text-align: center; margin: 20px 0; }
      .metrics { display: flex; justify-content: space-around; margin: 20px 0; border: 4px solid #00C853; padding: 20px; background-color: #F4C430; box-shadow: 8px 8px 0px #00C853; }
      .metric { text-align: center; color: #00C853; text-transform: uppercase; font-weight: bold; }
      .metric-value { font-size: 32px; font-weight: 900; color: #00C853; }
      .severity { display: inline-block; padding: 4px 12px; border: 2px solid #00C853; font-weight: 900; text-transform: uppercase; }
      .severity-high, .severity-critical { background: #D94A3D; color: white; }
      .severity-medium { background: #F4C430; color: #00C853; }
      .severity-low { background: #2D4CC8; color: white; }
      ul { list-style-type: none; padding-left: 0; }
      li { padding: 12px; border-bottom: 2px solid #00C853; font-weight: bold; }
      .action { margin: 15px 0; padding: 15px; background: white; border: 4px solid #00C853; box-shadow: 4px 4px 0px #D94A3D; font-weight: bold; }
      .confidence { color: #2D4CC8; font-weight: 900; text-transform: uppercase; }
      .timestamp { color: #00C853; font-size: 14px; font-weight: bold; text-transform: uppercase; }
      @media print {
        body { margin: 0; }
        .metrics, .action, h2 { box-shadow: none; border: 2px solid #00C853; }
      }
    </style>
</head>
<body>
  <h1>🧠 ReMem Cognitive Analysis Report</h1>
  <p class="timestamp">Analysis ID: ${result.id}<br>Generated: ${ensureDate(result.timestamp).toLocaleString()}</p>
  
  <h2>Cognitive Recovery Score</h2>
  <div class="score">${result.recoveryScore.overall}/100</div>
  <div class="metrics">
    <div class="metric">
      <div class="metric-value">${result.recoveryScore.contextCompleteness}%</div>
      <div>Context Completeness</div>
    </div>
    <div class="metric">
      <div class="metric-value">${result.recoveryScore.threadClarity}%</div>
      <div>Thread Clarity</div>
    </div>
    <div class="metric">
      <div class="metric-value">${result.recoveryScore.actionability}%</div>
      <div>Actionability</div>
    </div>
  </div>
  
  <h2>⚖️ Prosecutor Analysis</h2>
  <h3>What Went Wrong</h3>
  <ul>
    ${result.prosecutorDefense.prosecutor.issues.map(issue => `<li>${issue}</li>`).join('')}
  </ul>
  <p><strong>Severity:</strong> <span class="severity severity-${result.prosecutorDefense.prosecutor.severity.toLowerCase()}">${result.prosecutorDefense.prosecutor.severity}</span></p>
  
  <h2>🛡️ Defense Reasoning</h2>
  <h3>Why It Made Sense</h3>
  <ul>
    ${result.prosecutorDefense.defense.reasons.map(reason => `<li>${reason}</li>`).join('')}
  </ul>
  <p><strong>Context:</strong> ${result.prosecutorDefense.defense.context}</p>
  
  <h2>⚖️ Judge Summary</h2>
  <p><strong>Verdict:</strong> ${result.prosecutorDefense.judge.verdict}</p>
  <p><strong>Key Insight:</strong><br>${result.prosecutorDefense.judge.keyInsight}</p>
  <p><strong>Recommendation:</strong><br>${result.prosecutorDefense.judge.recommendation}</p>
  
  <h2>🎯 Most Likely Next Actions</h2>
  ${result.nextActions.map((action, index) => `
    <div class="action">
      <strong>${index + 1}.</strong> ${action.action}<br>
      <span class="confidence">Confidence: ${action.confidence}%</span>
    </div>
  `).join('')}
  
  ${result.gitTimeline ? `
    <h2>📊 Git Timeline</h2>
    <ul>
      ${result.gitTimeline.map(commit => `
        <li>
          <strong>[${commit.type}]</strong> ${commit.message}<br>
          <small>${commit.author} - ${ensureDate(commit.date).toLocaleDateString()}</small>
        </li>
      `).join('')}
    </ul>
  ` : ''}
  
  <hr style="margin: 40px 0;">
  <p style="text-align: center; color: #999; font-size: 14px;">
    Generated by ReMem - Cognitive Restoration Engine<br>
    Remember where your mind left off.
  </p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  downloadFile(blob, `remem-analysis-${result.id}.html`);
}

/**
 * Generate shareable link
 */
export function generateShareLink(result: AnalysisResult): string {
  // In a real implementation, this would:
  // 1. Store the result in a database
  // 2. Generate a unique short ID
  // 3. Return a shareable URL
  
  // For now, we'll create a data URL that can be shared
  const data = btoa(JSON.stringify({
    id: result.id,
    timestamp: result.timestamp,
    recoveryScore: result.recoveryScore,
    prosecutorDefense: result.prosecutorDefense,
    nextActions: result.nextActions,
  }));
  
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  return `${baseUrl}/share/${result.id}?data=${data}`;
}

/**
 * Copy share link to clipboard
 */
export async function copyShareLink(result: AnalysisResult): Promise<boolean> {
  try {
    const link = generateShareLink(result);
    await navigator.clipboard.writeText(link);
    return true;
  } catch (error) {
    console.error('Failed to copy link:', error);
    return false;
  }
}

/**
 * Helper function to download a file
 */
function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export analysis result optimized for Agentic IDEs (Cursor, Windsurf, GitHub Copilot)
 * Generates a comprehensive, single-prompt output with all context needed for AI agents
 */
export function exportForAgenticIDE(result: AnalysisResult): string {
  const timestampDate = ensureDate(result.timestamp);
  const timestamp = timestampDate.toISOString();
  const date = timestampDate.toLocaleString();
  
  // Build comprehensive prompt
  const prompt = `# 🤖 AGENTIC IDE CONTEXT EXPORT
## Generated by ReMem Cognitive Restoration Engine

**Analysis ID:** ${result.id}
**Timestamp:** ${date} (${timestamp})
**Recovery Score:** ${result.recoveryScore.overall}/100

---

## 📋 EXECUTIVE SUMMARY

This export contains a complete cognitive context reconstruction for an AI agent to understand and resolve the issue without requiring additional context or follow-up questions.

**Context Completeness:** ${result.recoveryScore.contextCompleteness}%
**Thread Clarity:** ${result.recoveryScore.threadClarity}%
**Actionability:** ${result.recoveryScore.actionability}%

---

## 🎯 PROBLEM SUMMARY

${result.prosecutorDefense.judge.verdict}

**Key Insight:**
${result.prosecutorDefense.judge.keyInsight}

**Recommended Action:**
${result.prosecutorDefense.judge.recommendation}

---

## ⚠️ IDENTIFIED ISSUES (Prosecutor Analysis)

**Severity Level:** ${result.prosecutorDefense.prosecutor.severity}

${result.prosecutorDefense.prosecutor.issues.map((issue, idx) => `${idx + 1}. ${issue}`).join('\n')}

---

## 🛡️ CONTEXTUAL REASONING (Defense Analysis)

**Context Validity:** ${result.prosecutorDefense.defense.context}

**Why This Happened:**
${result.prosecutorDefense.defense.reasons.map((reason, idx) => `${idx + 1}. ${reason}`).join('\n')}

---

## 🔍 ERROR DETAILS & STACK TRACES

${result.inputText.includes('Error:') || result.inputText.includes('Exception') || result.inputText.includes('at ') ? `
### Stack Trace Information

\`\`\`
${extractStackTraces(result.inputText)}
\`\`\`

### Error Messages

${extractErrorMessages(result.inputText)}
` : '_No explicit error traces detected in the input._'}

---

## 📊 DETECTED CONTENT ANALYSIS

- **Terminal Logs:** ${result.detectedContent.terminalLogs} occurrences
- **TODO Items:** ${result.detectedContent.todoItems} items
- **Error Traces:** ${result.detectedContent.errorTraces} traces
- **AI Conversations:** ${result.detectedContent.aiConversations} conversations
- **Code Snippets:** ${result.detectedContent.codeSnippets} snippets

---

## 💡 RECOMMENDED NEXT ACTIONS

${result.nextActions.map((action, idx) => `
### ${idx + 1}. ${action.action}
- **Confidence:** ${action.confidence}%
- **Priority:** ${action.priority}
`).join('\n')}

---

## 📁 FILE REFERENCES & CODE CONTEXT

${extractFileReferences(result.inputText)}

---

${result.gitTimeline ? `## 📜 GIT TIMELINE CONTEXT

${result.gitTimeline.map(commit => `
### [${commit.type.toUpperCase()}] ${commit.message}
- **Author:** ${commit.author}
- **Date:** ${ensureDate(commit.date).toLocaleDateString()}
- **Hash:** ${commit.hash}
`).join('\n')}

---

` : ''}
## 🧠 ORIGINAL COGNITIVE FRAGMENTS

The following is the raw input that was analyzed. This provides complete context for understanding the developer's mental state and debugging journey:

\`\`\`
${result.inputText}
\`\`\`

---

## 🔧 DEBUGGING SUGGESTIONS FOR AI AGENT

Based on the analysis, here are specific actions the AI agent should take:

1. **Immediate Focus Areas:**
   ${result.prosecutorDefense.prosecutor.severity === 'CRITICAL' || result.prosecutorDefense.prosecutor.severity === 'HIGH'
     ? '- Address critical issues first to prevent system failure\n   - Implement error boundaries and fallback mechanisms'
     : '- Review and optimize the identified areas\n   - Implement best practices and preventive measures'}

2. **Code Review Priorities:**
   - Files mentioned in error traces (see File References section)
   - Functions/methods in the stack trace
   - Related configuration files

3. **Testing Strategy:**
   - Add unit tests for error scenarios
   - Implement integration tests for critical paths
   - Add error boundary tests for UI components

4. **Documentation Needs:**
   - Document the root cause and resolution
   - Update troubleshooting guides
   - Add inline comments for complex logic

---

## 📝 METADATA FOR AI PROCESSING

\`\`\`json
{
  "analysisId": "${result.id}",
  "timestamp": "${timestamp}",
  "recoveryScore": {
    "overall": ${result.recoveryScore.overall},
    "contextCompleteness": ${result.recoveryScore.contextCompleteness},
    "threadClarity": ${result.recoveryScore.threadClarity},
    "actionability": ${result.recoveryScore.actionability}
  },
  "severity": "${result.prosecutorDefense.prosecutor.severity}",
  "contextValidity": "${result.prosecutorDefense.defense.context}",
  "detectedContent": ${JSON.stringify(result.detectedContent, null, 2)},
  "hasGitContext": ${!!result.gitTimeline},
  "issueCount": ${result.prosecutorDefense.prosecutor.issues.length},
  "actionCount": ${result.nextActions.length}${result.metadata ? `,
  "processingMetadata": ${JSON.stringify(result.metadata, null, 2)}` : ''}
}
\`\`\`

---

## 🎯 PROMPT FOR AI AGENT

**You are an expert software engineer tasked with resolving the issues described above.**

Given the complete context provided (errors, stack traces, cognitive fragments, git history, and analysis), please:

1. Identify the root cause of the primary issue
2. Propose a concrete solution with code examples
3. Explain potential side effects or considerations
4. Suggest preventive measures for the future
5. Provide step-by-step implementation guidance

**Focus on:** ${result.prosecutorDefense.judge.recommendation}

**Priority Level:** ${result.prosecutorDefense.prosecutor.severity}

---

*Generated by ReMem - Cognitive Restoration Engine*
*Optimized for: Cursor, Windsurf, GitHub Copilot, and other agentic IDEs*
*Format: Markdown with embedded code blocks and JSON metadata*
`;

  return prompt;
}

/**
 * Copy agentic IDE export to clipboard
 */
export async function copyAgenticIDEExport(result: AnalysisResult): Promise<boolean> {
  try {
    const exportContent = exportForAgenticIDE(result);
    await navigator.clipboard.writeText(exportContent);
    return true;
  } catch (error) {
    console.error('Failed to copy agentic IDE export:', error);
    return false;
  }
}

/**
 * Download agentic IDE export as markdown file
 */
export function downloadAgenticIDEExport(result: AnalysisResult): void {
  const content = exportForAgenticIDE(result);
  const blob = new Blob([content], { type: 'text/markdown' });
  downloadFile(blob, `remem-agentic-export-${result.id}.md`);
}

/**
 * Helper: Extract stack traces from text
 */
function extractStackTraces(text: string): string {
  const stackTracePatterns = [
    /at .+?\(.+?:\d+:\d+\)/g,
    /at .+?:\d+:\d+/g,
    /File ".+?", line \d+/g,
  ];
  
  const traces: string[] = [];
  for (const pattern of stackTracePatterns) {
    const matches = text.match(pattern);
    if (matches) {
      traces.push(...matches);
    }
  }
  
  return traces.length > 0
    ? traces.slice(0, 20).join('\n')
    : 'No stack traces detected';
}

/**
 * Helper: Extract error messages from text
 */
function extractErrorMessages(text: string): string {
  const errorPatterns = [
    /Error: .+/g,
    /Exception: .+/g,
    /ERROR: .+/g,
    /FAILED: .+/g,
  ];
  
  const errors: string[] = [];
  for (const pattern of errorPatterns) {
    const matches = text.match(pattern);
    if (matches) {
      errors.push(...matches);
    }
  }
  
  return errors.length > 0
    ? errors.slice(0, 10).map(err => `- ${err}`).join('\n')
    : '_No explicit error messages found._';
}

/**
 * Helper: Extract file references from text
 */
function extractFileReferences(text: string): string {
  const filePatterns = [
    /(?:^|\s)([a-zA-Z0-9_\-./]+\.[a-zA-Z0-9]+)(?:\s|$|:)/g,
    /at .+?\((.+?:\d+:\d+)\)/g,
    /File "(.+?)", line \d+/g,
  ];
  
  const files = new Set<string>();
  for (const pattern of filePatterns) {
    let match;
    while ((match = pattern.exec(text)) !== null) {
      if (match[1]) {
        files.add(match[1]);
      }
    }
  }
  
  if (files.size === 0) {
    return '_No specific file references detected. Review the original input for context._';
  }
  
  return Array.from(files)
    .slice(0, 20)
    .map(file => `- \`${file}\``)
    .join('\n');
}

// Made with Bob